# Generated by Django 5.1.1 on 2024-10-25 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airQualityApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Device',
            new_name='device_name',
        ),
    ]
