# Generated by Django 5.1.1 on 2024-10-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airQualityApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='address',
            new_name='serial_number',
        ),
    ]
